### ISSUE TITLE
Add AMMCreate Fee description

### ISSUE THREAD

**Issue by develoQ** [ripple/opensource.ripple.com#44]
In an `AMMCreate` transaction, the `Fee` field must be an amount greater than or equal to one owner reserve, but there appears to be no mention of this.

Also in the AMMCreate transaction example, 10drop is specified, which should also be corrected.

**Comment by mDuo13** [comment]
The tutorial was updated to mention this when the spec changed, but I neglected to update the AMMCreate transaction type page. Fixed in #58.
