### ISSUE TITLE
Incorrect command/method name displayed for `amm_info`

### ISSUE THREAD

**Issue by wonj1012** [ripple/opensource.ripple.com#49]
I've noticed a potential bug in the display of the command/method name on the [amm_info documentation page](https://opensource.ripple.com/docs/xls-30d-amm/public-api-methods/amm_info/).

![Screenshot](https://github.com/ripple/opensource.ripple.com/assets/88670151/5446160a-34b1-4991-bda6-673939432ada)

The command/method name appears to be displayed incorrectly.  
Please review the documentation at [this location in the repository](https://github.com/ripple/opensource.ripple.com/blob/main/docs/xls-30d-amm/public-api-methods/amm_info.md) to address the issue.  
I believe the correct name should be `amm_info`, or if it's a placeholder, it should be updated to the appropriate value.

Thank you for looking into this.

**Comment by mDuo13** [comment]
Yup, this is a formatting error resulting from when the page was ported from the xrpl-dev-portal repository to this one. (The preprocessor there processes that into the page name, which is `amm_info`.

**Comment by mDuo13** [comment]
Fixed in #58.
